apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: example-app-devfile-sample-xmnr-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: example-app-devfile-sample-xmnr-sample
    app.kubernetes.io/part-of: example-app
  name: example-app-devfile-sample-xmnr-sample
  namespace: khala-1-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: example-app-devfile-sample-xmnr-sample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: example-app-devfile-sample-xmnr-sample
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:khala-1-tenant-example-app-devfile-sample-xmnr-sample
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 3001
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 3001
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
