apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: example-app-devfile-sample-xmnr-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: example-app-devfile-sample-xmnr-sample
    app.kubernetes.io/part-of: example-app
  name: example-app-devfile-sample-xmnr-sample
  namespace: khala-1-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: example-app-devfile-sample-xmnr-sample
status:
  loadBalancer: {}
